### ISSUE TITLE
After running the example, the win10 icon is incomplete.

### ISSUE THREAD

**Issue by chenweibo** [nklayman/electron-icon-example#1]
Replace the root directory icon.png
Run npm run electron:generate-icon
Run npm run electron:build -- --win
Found that the icon on win10 is less than half

![xnip2019-03-02_16-28-45](https://user-images.githubusercontent.com/19586007/53679515-6250b580-3d08-11e9-8190-09e9efc6002f.jpg)

![xnip2019-03-02_16-29-17](https://user-images.githubusercontent.com/19586007/53679524-6e3c7780-3d08-11e9-9410-b8bcf16fbb72.jpg)

Packaging the mac version of the icon is normal

**Comment by nklayman** [comment]
Can you check the icon.ico image inside of the build/icons directory and see if the top is chopped off there?

**Comment by chenweibo** [comment]
I removed the icons folder. Moving icon.png from icons to build found normal. Image is not missing

**Comment by nklayman** [comment]
It works now, correct?

**Comment by chenweibo** [comment]
its work now
