### ISSUE TITLE
Does not work on Linux Ubuntu

### ISSUE THREAD

**Issue by LucasHild** [nklayman/electron-icon-example#2]
The example does not work on Linux Ubunu.

I started the program using the following command:

```
npm run electron:build
./dist_electron/electron-test\ 0.1.0.AppImage
```

But it only shows the default icon of my OS:

![image](https://user-images.githubusercontent.com/20486366/53683412-ce2f2000-3d00-11e9-9a3e-fda7dbbfa871.png)

**Comment by nklayman** [comment]
I moved the icon to `public` so it would be included in the final build. I then told electron to use the icon with:
```js
win = new BrowserWindow({
    width: 800,
    height: 600,
    icon: path.join(__static, 'icon.png')
  })
```

**Comment by nklayman** [comment]
Also, make sure to upgrade your deps as there was a weird issue where the `icon.png` in `public` would be ignored.
