### ISSUE TITLE
Delete the png build icon below 128x128 by test.

### ISSUE THREAD

**Issue by chenweibo** [nklayman/electron-icon-example#3]
The previous problem was that the icon was missing after packaging and thought it was a problem with the path. Later, I packaged it several times and found that 12 times was normal, and there was a missing problem. I finally deleted the image below 128 pixels. There were no problems with the test several times. I suspect that it is possible to generate too many size images, will it be Randomly taken? Packaged from win10 The image of the installer is blurred like a small size map, and the taskbar icon is blurred but is missing. It is suspected to refer to the image below 128, and everything is normal after deletion. No blur

**Comment by nklayman** [comment]
The resizing of icons is handled by [electron icon builder](https://www.npmjs.com/package/electron-icon-builder), and the injection of the icon into the executable is handled by [electron builder](https://electron.build). It seems like you are having issues with one of those packages, open an issue there instead.
