### ISSUE TITLE
Finder icon broken on Catalina

### ISSUE THREAD

**Issue by bobmoff** [nklayman/electron-icon-example#5]
![Screenshot 2019-10-17 18 10 54](https://user-images.githubusercontent.com/1033236/67027310-98ad3a80-f109-11e9-8c8d-b119dec9da46.png)

This is what it looks like when building this project.

If I remove all icons and instead move the original icon.png to the build-folder, it works fine.

What is the need for all these different sizes and formats if it works without them ?

**Comment by philippkuehn** [comment]
Same here :(

**Comment by pmburov** [comment]
Sadly, problem is still here

**Comment by talyguryn** [comment]
problem is still here.
bad look on win too. codex-team/devops-toolbox-app#20

**Comment by nklayman** [comment]
I'm not sure if something changed or if I just missed it when I first made this guide, but it seems that just adding and `icon.png` in `build/icons` is all you need to do for icons to work on all platforms. I've removed all the extra stuff from the documentation site and it no longer links to this repo as it's so simple an example isn't necessary. I will archive this repo as it is not accurate.
